export const ActionTypes = {
  SET_POSTS: "SET_POSTS",
  SET_SINGLE_POST: "SET_SINGLE_POST",
  REMOVE_SINGLE_POST_FROM_STATE: "REMOVE_SINGLE_POST_FROM_STATE",
  SET_USERS: "SET_USERS",
  REMOVE_USERS: "REMOVE_USERS",
};
